
import React, { useEffect, useState, useCallback } from 'react';
import { Story, ImageMap } from '../types';
import { generateIllustration } from '../services/geminiService';
import { Button } from './Button';
import { ChevronLeft, ChevronRight, RefreshCw, BookOpen, RotateCcw, Map, Users } from 'lucide-react';

interface BookReaderProps {
  story: Story;
  onReset: () => void;
}

export const BookReader: React.FC<BookReaderProps> = ({ story, onReset }) => {
  const [currentPage, setCurrentPage] = useState(0);
  const [images, setImages] = useState<ImageMap>({});
  const [loadingImages, setLoadingImages] = useState<Record<number, boolean>>({});

  // Page Structure:
  // 0: Cover
  // 1: World Building (New)
  // 2: Characters (New)
  // 3..(N+2): Chapters
  // N+3: Ending
  const SPECIAL_PAGES = 3; // Cover + World + Characters
  const totalPages = story.chapters.length + SPECIAL_PAGES + 1; 

  const isCover = currentPage === 0;
  const isWorldPage = currentPage === 1;
  const isCharacterPage = currentPage === 2;
  const isEnding = currentPage === totalPages - 1;
  const isChapter = !isCover && !isWorldPage && !isCharacterPage && !isEnding;
  
  const chapterIndex = currentPage - SPECIAL_PAGES;
  const currentChapter = isChapter ? story.chapters[chapterIndex] : null;

  // Determine the prompt for the current page
  const getCurrentPrompt = useCallback(() => {
    if (isCover) {
      return `A magical book cover for a story titled "${story.title}". The cover art should depict: ${story.chapters[0]?.imagePrompt || 'a mystery'}. No text on the book cover art.`;
    }
    if (isWorldPage) {
      return `A wide detailed landscape shot establishing the setting: ${story.world.geography}. Atmosphere: ${story.world.atmosphere}. Pixar style concept art.`;
    }
    if (isCharacterPage) {
      const charDesc = story.characters.map(c => c.description).join(" and ");
      return `A group character lineup of: ${charDesc}. Pixar style character design sheet, neutral background.`;
    }
    if (isEnding) {
        return `A peaceful ending scene for the story "${story.title}". Soft lighting, closing the book, emotional resonance.`;
    }
    return currentChapter?.imagePrompt || "";
  }, [isCover, isWorldPage, isCharacterPage, isEnding, currentChapter, story]);

  // Handle Image Generation
  const fetchImageForPage = useCallback(async (pageIndex: number, prompt: string) => {
    if (images[pageIndex] || loadingImages[pageIndex]) return;

    setLoadingImages(prev => ({ ...prev, [pageIndex]: true }));
    try {
      const base64 = await generateIllustration(prompt);
      setImages(prev => ({ ...prev, [pageIndex]: base64 }));
    } catch (err) {
      console.error(`Failed to generate image for page ${pageIndex}`, err);
    } finally {
      setLoadingImages(prev => ({ ...prev, [pageIndex]: false }));
    }
  }, [images, loadingImages]);

  // Trigger generation when page changes
  useEffect(() => {
    const prompt = getCurrentPrompt();
    if (prompt) {
      fetchImageForPage(currentPage, prompt);
    }
    
    // Pre-fetch logic could be expanded, but keeping it simple for now
  }, [currentPage, getCurrentPrompt, fetchImageForPage]);

  const handleNext = () => {
    if (currentPage < totalPages - 1) {
      setCurrentPage(p => p + 1);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const handlePrev = () => {
    if (currentPage > 0) {
      setCurrentPage(p => p - 1);
      window.scrollTo({ top: 0, behavior: 'smooth' });
    }
  };

  const currentImage = images[currentPage];
  const isImageLoading = loadingImages[currentPage];

  const renderContent = () => {
    if (isCover) {
      return (
        <div className="text-center space-y-8 animate-fade-in-up">
          <span className="text-magic uppercase tracking-widest text-xs font-bold">Presenting</span>
          <h1 className="text-5xl md:text-6xl font-serif text-ink font-bold leading-tight">
            {story.title}
          </h1>
          <div className="w-16 h-1 bg-magic mx-auto rounded-full opacity-50"></div>
          <p className="text-gray-500 italic font-serif text-lg">
            A visual journey generated by AI
          </p>
        </div>
      );
    }

    if (isWorldPage) {
      return (
        <div className="space-y-6 animate-fade-in-up">
          <div className="flex items-center gap-2 text-magic text-sm font-bold uppercase tracking-wider">
            <Map className="w-4 h-4" />
            <span>The World</span>
          </div>
          <h2 className="text-3xl font-serif font-bold text-ink">Setting the Scene</h2>
          
          <div className="space-y-4">
             <div>
                <h3 className="font-bold text-gray-700 font-serif text-lg">Geography</h3>
                <p className="font-serif text-gray-600">{story.world.geography}</p>
             </div>
             <div>
                <h3 className="font-bold text-gray-700 font-serif text-lg">Atmosphere</h3>
                <p className="font-serif text-gray-600">{story.world.atmosphere}</p>
             </div>
             <div>
                <h3 className="font-bold text-gray-700 font-serif text-lg">Culture</h3>
                <p className="font-serif text-gray-600">{story.world.culture}</p>
             </div>
          </div>
        </div>
      );
    }

    if (isCharacterPage) {
        return (
          <div className="space-y-6 animate-fade-in-up">
            <div className="flex items-center gap-2 text-magic text-sm font-bold uppercase tracking-wider">
              <Users className="w-4 h-4" />
              <span>Dramatis Personae</span>
            </div>
            <h2 className="text-3xl font-serif font-bold text-ink">The Cast</h2>
            
            <div className="space-y-6">
                {story.characters.map((char, idx) => (
                    <div key={idx} className="border-l-2 border-purple-200 pl-4">
                        <h3 className="font-bold text-xl text-ink font-serif">{char.name}</h3>
                        <p className="text-sm text-gray-500 italic mb-2">{char.traits}</p>
                        <p className="font-serif text-gray-700">{char.backstory}</p>
                        <p className="text-xs text-gray-400 mt-2">Appearance: {char.description}</p>
                    </div>
                ))}
            </div>
          </div>
        );
      }

    if (currentChapter) {
        // Find plot info for this chapter
        const plotPoint = story.plotOutline.find(p => p.chapterIndex === chapterIndex);
        
        return (
            <div className="space-y-6 animate-fade-in-up">
              <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2 text-magic text-sm font-bold uppercase tracking-wider">
                    <span>Chapter {chapterIndex + 1}</span>
                    <span className="w-8 h-px bg-stone-200"></span>
                  </div>
                  {currentChapter.plotType && (
                      <span className="text-xs text-gray-400 bg-gray-100 px-2 py-1 rounded-full uppercase tracking-wider font-bold">
                          {currentChapter.plotType}
                      </span>
                  )}
              </div>
              
              <h2 className="text-3xl font-serif font-bold text-ink">{currentChapter.title}</h2>
              <p className="text-lg leading-relaxed font-serif text-gray-700">
                {currentChapter.content}
              </p>

              {plotPoint && (
                <div className="mt-8 p-4 bg-purple-50 rounded-lg text-sm text-purple-800 font-serif border border-purple-100">
                    <span className="font-bold block mb-1 uppercase text-xs tracking-wider">Story Arc Note</span>
                    {plotPoint.description}
                </div>
              )}
            </div>
        );
    }

    if (isEnding) {
      return (
        <div className="text-center space-y-6 animate-fade-in-up">
          <h2 className="text-3xl font-serif font-bold text-ink">The End</h2>
          <p className="text-xl leading-relaxed font-serif text-gray-700 italic">
            {story.ending}
          </p>
          <div className="pt-8">
             <Button onClick={onReset} className="mx-auto">
                Create Another Story
             </Button>
          </div>
        </div>
      );
    }
    return null;
  };

  return (
    <div className="flex flex-col min-h-screen max-w-5xl mx-auto p-4 md:p-8">
      {/* Header / Navigation Controls */}
      <div className="flex justify-between items-center mb-6">
        <Button variant="ghost" onClick={onReset} className="text-sm">
          <RotateCcw className="w-4 h-4 mr-2" />
          New Story
        </Button>
        <div className="text-gray-400 font-serif italic text-sm">
          Page {currentPage + 1} of {totalPages}
        </div>
      </div>

      {/* Main Book Content Area */}
      <div className="flex-1 bg-paper rounded-2xl shadow-2xl overflow-hidden flex flex-col md:flex-row border border-stone-200 min-h-[600px]">
        
        {/* Left Side: Visuals */}
        <div className="md:w-1/2 bg-stone-100 relative flex items-center justify-center overflow-hidden min-h-[300px] md:min-h-auto border-b md:border-b-0 md:border-r border-stone-200">
          {currentImage ? (
            <img 
              src={currentImage} 
              alt="Story illustration" 
              className="w-full h-full object-cover animate-fade-in"
            />
          ) : (
            <div className="text-center p-8 text-gray-400 flex flex-col items-center">
               {isImageLoading ? (
                 <>
                   <RefreshCw className="w-8 h-8 animate-spin mb-4 text-magic" />
                   <p className="font-serif italic animate-pulse">Bringing scene to life...</p>
                 </>
               ) : (
                 <div className="flex flex-col items-center gap-4">
                    <p>Image not available</p>
                    <Button 
                        variant="secondary" 
                        onClick={() => fetchImageForPage(currentPage, getCurrentPrompt())}
                        className="text-xs py-2 px-4"
                    >
                        Retry
                    </Button>
                 </div>
               )}
            </div>
          )}
        </div>

        {/* Right Side: Text */}
        <div className="md:w-1/2 p-8 md:p-12 flex flex-col justify-center relative bg-paper overflow-y-auto max-h-[800px]">
           {/* Decorative corner */}
           <div className="absolute top-4 right-4 text-stone-200 pointer-events-none">
               <BookOpen className="w-12 h-12 opacity-20" />
           </div>

           <div className="max-w-md mx-auto w-full">
              {renderContent()}
           </div>
        </div>
      </div>

      {/* Navigation Footer */}
      <div className="flex justify-between items-center mt-8 px-4">
         <Button 
            variant="secondary" 
            onClick={handlePrev} 
            disabled={currentPage === 0}
            className="w-32"
         >
            <ChevronLeft className="w-4 h-4 mr-1" /> Previous
         </Button>

         {currentPage < totalPages - 1 && (
             <Button 
                variant="primary" 
                onClick={handleNext}
                className="w-32 shadow-magic/25"
             >
                Next <ChevronRight className="w-4 h-4 ml-1" />
             </Button>
         )}
      </div>
    </div>
  );
};
